// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: Grinder

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_iwLogo;
lv_obj_t * ui_loadingSlider;
lv_obj_t * ui_loadingLabel;
// CUSTOM VARIABLES


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
void ui_event_homeButton(lv_event_t * e);
lv_obj_t * ui_homeButton;
void ui_event_accountButton(lv_event_t * e);
lv_obj_t * ui_accountButton;
void ui_event_settingButton(lv_event_t * e);
lv_obj_t * ui_settingButton;
lv_obj_t * ui_sysTimeLable;
lv_obj_t * ui_sysDateLable;
lv_obj_t * ui_homePanel;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label7;
void ui_event_startupButton(lv_event_t * e);
lv_obj_t * ui_startupButton;
void ui_event_speedSetButton(lv_event_t * e);
lv_obj_t * ui_speedSetButton;
lv_obj_t * ui_speedSetLabel;
void ui_event_timeHourSetButton(lv_event_t * e);
lv_obj_t * ui_timeHourSetButton;
lv_obj_t * ui_timeHourSetLabel;
void ui_event_timeMinuteSetButton(lv_event_t * e);
lv_obj_t * ui_timeMinuteSetButton;
lv_obj_t * ui_timeMinuteSetLabel;
void ui_event_timeSecondSetButton(lv_event_t * e);
lv_obj_t * ui_timeSecondSetButton;
lv_obj_t * ui_timeSecondSetLabel;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Label6;
lv_obj_t * ui_motorSpeedChart;
lv_obj_t * ui_startupConfirmationPanel;
void ui_event_startupOkButton(lv_event_t * e);
lv_obj_t * ui_startupOkButton;
lv_obj_t * ui_Label8;
void ui_event_startupQuitButton(lv_event_t * e);
lv_obj_t * ui_startupQuitButton;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Label11;
lv_obj_t * ui_speedConfimationLabel;
lv_obj_t * ui_runTimeConfimationLabel;
lv_obj_t * ui_accountPanel;
lv_obj_t * ui_userImage;
lv_obj_t * ui_accountLabel;
lv_obj_t * ui_signUpButton;
lv_obj_t * ui_Label12;
lv_obj_t * ui_signInButton;
lv_obj_t * ui_Label13;
lv_obj_t * ui_fingerprintImage;
lv_obj_t * ui_Panel4;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_iw_logo_200x[1] = {&ui_img_iw_logo_200x106_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_homeButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_home_button_clicked(e);
    }
}

void ui_event_accountButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_account_button_clicked(e);
    }
}

void ui_event_settingButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_setting_button_clicked(e);
    }
}

void ui_event_startupButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_startup_button(e);
    }
}

void ui_event_speedSetButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        ui_event_set_motor_speed(e);
    }
}

void ui_event_timeHourSetButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        ui_event_set_time_hour(e);
    }
}

void ui_event_timeMinuteSetButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        ui_event_set_time_minute(e);
    }
}

void ui_event_timeSecondSetButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        ui_event_set_time_second(e);
    }
}

void ui_event_startupOkButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_startup_ok_button(e);
    }
}

void ui_event_startupQuitButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_startup_no_button(e);
    }
}

static void slider_value_increase_cb(lv_timer_t * timer)
{
    int current_value = lv_slider_get_value(ui_loadingSlider);
    if (current_value < 100) {
        lv_slider_set_value(ui_loadingSlider, current_value + 1, LV_ANIM_OFF);
    } else {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_Screen2_screen_init);
        lv_timer_del(timer);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);

    lv_timer_t * timer = lv_timer_create(slider_value_increase_cb, 15, NULL);
}
