// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: Grinder

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_event_home_button_clicked(lv_event_t * e);
void ui_event_account_button_clicked(lv_event_t * e);
void ui_event_setting_button_clicked(lv_event_t * e);
void ui_event_startup_button(lv_event_t * e);
void ui_event_set_motor_speed(lv_event_t * e);
void ui_event_set_time_hour(lv_event_t * e);
void ui_event_set_time_minute(lv_event_t * e);
void ui_event_set_time_second(lv_event_t * e);
void ui_event_startup_ok_button(lv_event_t * e);
void ui_event_startup_no_button(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
