// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: Grinder

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_iwLogo = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_iwLogo, &ui_img_iw_logo_200x106_png);
    lv_obj_set_width(ui_iwLogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_iwLogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_iwLogo, 0);
    lv_obj_set_y(ui_iwLogo, -40);
    lv_obj_set_align(ui_iwLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_iwLogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_iwLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_loadingSlider = lv_slider_create(ui_Screen1);
    lv_slider_set_value(ui_loadingSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_loadingSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_loadingSlider, 0,
                                                                                                  LV_ANIM_OFF);
    lv_obj_set_width(ui_loadingSlider, 200);
    lv_obj_set_height(ui_loadingSlider, 8);
    lv_obj_set_x(ui_loadingSlider, 0);
    lv_obj_set_y(ui_loadingSlider, 35);
    lv_obj_set_align(ui_loadingSlider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_loadingSlider, lv_color_hex(0xE0FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_loadingSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_loadingSlider, lv_color_hex(0x63B8FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_loadingSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_loadingSlider, lv_color_hex(0x63B8FF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_loadingSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_loadingSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_loadingSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_loadingSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_loadingSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_loadingLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_loadingLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_loadingLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_loadingLabel, 5);
    lv_obj_set_y(ui_loadingLabel, 52);
    lv_obj_set_align(ui_loadingLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_loadingLabel, "loading......");
    lv_obj_set_style_text_color(ui_loadingLabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_loadingLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_loadingLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);


}
