// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: Grinder

#ifndef _GRINDER_UI_H
#define _GRINDER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_iwLogo;
extern lv_obj_t * ui_loadingSlider;
extern lv_obj_t * ui_loadingLabel;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
void ui_event_homeButton(lv_event_t * e);
extern lv_obj_t * ui_homeButton;
void ui_event_accountButton(lv_event_t * e);
extern lv_obj_t * ui_accountButton;
void ui_event_settingButton(lv_event_t * e);
extern lv_obj_t * ui_settingButton;
extern lv_obj_t * ui_sysTimeLable;
extern lv_obj_t * ui_sysDateLable;
extern lv_obj_t * ui_homePanel;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label7;
void ui_event_startupButton(lv_event_t * e);
extern lv_obj_t * ui_startupButton;
void ui_event_speedSetButton(lv_event_t * e);
extern lv_obj_t * ui_speedSetButton;
extern lv_obj_t * ui_speedSetLabel;
void ui_event_timeHourSetButton(lv_event_t * e);
extern lv_obj_t * ui_timeHourSetButton;
extern lv_obj_t * ui_timeHourSetLabel;
void ui_event_timeMinuteSetButton(lv_event_t * e);
extern lv_obj_t * ui_timeMinuteSetButton;
extern lv_obj_t * ui_timeMinuteSetLabel;
void ui_event_timeSecondSetButton(lv_event_t * e);
extern lv_obj_t * ui_timeSecondSetButton;
extern lv_obj_t * ui_timeSecondSetLabel;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_motorSpeedChart;
extern lv_obj_t * ui_startupConfirmationPanel;
void ui_event_startupOkButton(lv_event_t * e);
extern lv_obj_t * ui_startupOkButton;
extern lv_obj_t * ui_Label8;
void ui_event_startupQuitButton(lv_event_t * e);
extern lv_obj_t * ui_startupQuitButton;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_speedConfimationLabel;
extern lv_obj_t * ui_runTimeConfimationLabel;
extern lv_obj_t * ui_accountPanel;
extern lv_obj_t * ui_userImage;
extern lv_obj_t * ui_accountLabel;
extern lv_obj_t * ui_signUpButton;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_signInButton;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_fingerprintImage;
extern lv_obj_t * ui_Panel4;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_iw_logo_200x106_png);    // assets/iw_logo_200x106.png
LV_IMG_DECLARE(ui_img_home_checked_icon_png);    // assets/home_checked_icon.png
LV_IMG_DECLARE(ui_img_home_unchecked_icon_png);
LV_IMG_DECLARE(ui_img_account_checked_png);    // assets/account_unchecked.png
LV_IMG_DECLARE(ui_img_account_unchecked_png);
LV_IMG_DECLARE(ui_img_setting_checked_icon_png);    // assets/setting_unchecked_icon.png
LV_IMG_DECLARE(ui_img_setting_unchecked_icon_png);
LV_IMG_DECLARE(ui_img_start_png);    // assets/start.png
LV_IMG_DECLARE(ui_img_stop_png);
LV_IMG_DECLARE(ui_img_user_sign_out_png);    // assets/User_sign_out.png
LV_IMG_DECLARE(ui_img_fingerprint_unchecked_png);    // assets/fingerprint_unchecked.png

// FONTS
LV_FONT_DECLARE(ui_font_Font_cn_28);
LV_FONT_DECLARE(ui_font_Font_cn_36);
LV_FONT_DECLARE(ui_font_Font_num_86);
LV_FONT_DECLARE(ui_font_Font_number_64);
LV_FONT_DECLARE(ui_font_Font_cn_25);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
